name: Cargo Audit

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  HUSKY: 0

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run Cargo Audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
